CREATE TABLE Travel (
    _id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL COLLATE NOCASE,
    Ship TEXT NOT NULL COLLATE NOCASE,
    Customer TEXT NOT NULL COLLATE NOCASE,
    Status INTEGER NOT NULL,
    Import_Time DATETIME NOT NULL
);

CREATE TABLE Movement (
    _id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    BillToLading TEXT NOT NULL COLLATE NOCASE,
    Travel_Id INTEGER NOT NULL,
    Desired_Quantity REAL NOT NULL,
    Conferred_Quantity REAL NOT NULL
);

CREATE TABLE Manifested (
    _id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    Ship TEXT NOT NULL COLLATE NOCASE,
    Customer TEXT NOT NULL COLLATE NOCASE,
    Bill_To_Lading TEXT NOT NULL COLLATE NOCASE,
    Serie TEXT NOT NULL,
    Product TEXT NOT NULL COLLATE NOCASE,
    Cross_Weight INTEGER NOT NULL,
    Net_Weight INTEGER NOT NULL
);

CREATE TABLE Conference (
    _id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    Serie TEXT NOT NULL COLLATE NOCASE,
    Movement_Id INTEGER NOT NULL,
    Dimension_Id INTEGER NOT NULL,
    Conference_Time DATETIME NOT NULL,
    Notes TEXT NOT NULL COLLATE NOCASE
);

CREATE TABLE Dimension (
    _id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    Weight REAL NOT NULL,
    Thickness TEXT NOT NULL
);

CREATE TABLE Image (
    _id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    Conference_id INTEGER NOT NULL,
    URL TEXT NOT NULL
);